server:
  port: 18500
spring:
  cloud:
    consul:
      discovery:
        health-check-interval: 15s
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}:${server.port}
        prefer-ip-address: true
      host: #{linux-ip}
      port: 8500
  application:
    name: test-project

# apollo集成
app:
  id: test-config # apollo 配置应用的 appid
apollo:
  meta: http://#{linux-ip}:8080 # apollo meta-server地址，一般同config-server地址
  bootstrap:
    namespaces: application # apollo 使用配置的命名空间，多个以逗号分隔 配置优先级从大到小